greatest_hits = [
    "bob seger & the silver bullet band",
    "rascal flatts",
]
pop_country_albums = [
    "9",
    "35 greatest hits",
    "50 number ones",
    "a star is born (soundtrack)",
    "across generations",
    "alicia",
    "all about luv",
    "all of it",
    "anti",
    "artist 2.0",
    "astroworld",
    "behind the bar",
    "born here live here die here",
    "championships",
    "changes",
    "christmas",
    "chromatica",
    "crash my party",
    "dark lane demo tapes",
    "different 'round here",
    "ella mai",
    "father of asahd",
    "fire & brimstone",
    "for you",
    "frayed at both ends",
    "girl",
    "got what i got",
    "graduation",
    "greatest hits volume 1",
    "guardians of the galaxy: awesome mix vol. 1",
    "heartache medication",
    "here on earth",
    "hot pink",
    "i am… sasha fierce",
    "icon: greatest hits",
    "if it wasn't for trucks",
    "jesus is king",
    "judas and the black messiah: the inspired album",
    "justice",
    "kane brown",
    "live at the cma theater in the country music hall of fame",
    "need a bar sometimes",
    "night visions",
    "no depression in heaven",
    "nobody is listening",
    "nothing was the same",
    "perfect ten",
    "please excuse me for being antisocial",
    "pray for the wicked",
    "purpose",
    "rearview town",
    "red pill blues",
    "scorpion",
    "strait out of the box",
    "sugar & joy",
    "teenage dream",
    "the american farewell tour",
    "the big day",
    "the ultimate hits",
    "The Way I Wanna Go ",
    "total freedom",
    "translation",
    "twenty years of rascal flatts",
    "victory lap",
    "what you see is what you get",
    "yummy",
]
