# These are US controlled songs for Pop and Country
pop_country_songs = [
    "ain't always the cowboy",
    "alabama people",
    "all around me",
    "all time low",
    "ballin'",
    "banjo",
    "better at being who i am",
    "better days",
    "bettin' man",
    "blame it",
    "blame it on you",
    "blue trash",
    "boo d up",
    "broken cowboy",
    "bye mom",
    "came here to drink",
    "can't feel my face",
    "carolina",
    "championships",
    "changed",
    "cold water",
    "come around me",
    "cowboy killer",
    "crawdaddy served cold",
    "dear today",
    "dedication",
    "despacito (remix) [feat. justin bieber]",
    "die alone",
    "diamond ring",
    "dinero",
    "dirt to dust",
    "dirt we were raised on",
    "don't go",
    "earned it",
    "easy",
    "ever since new york",
    "everything i am",
    "fat little killer boy",
    "flatliner",
    "from the dining table",
    "gettin' warmed up",
    "girl like me",
    "girl like you",
    "good woman",
    "got what i got",
    "green light",
    "hell of a night",
    "high noon neon",
    "higher",
    "i don't drink anymore",
    "i feel it coming",
    "i know she still loves me",
    "i'll wait for you",
    "if i didn't wear boots",
    "if it wasn't for trucks",
    "in a truck right now",
    "in my blood",
    "in my feelings",
    "intentions",
    "ispy",
    "jealous",
    "jesus is lord",
    "keeping it small town",
    "kiwi",
    "last time that i checc'd",
    "lean on",
    "let me love you",
    "liability",
    "little more (royalty)",
    "love you too late",
    "low life",
    "make me (cry)",
    "mayberry",
    "meet me in the hallway",
    "my first everything",
    "need a bar sometimes",
    "one for the road",
    "only angel",
    "outlaws like us",
    "panda",
    "party monster",
    "pray",
    "peaches",
    "rearview town",
    "reason to drink",
    "renegades",
    "respect the game",
    "riot",
    "same old song",
    "selah",
    "set it off",
    "shape shifter",
    "she likes it",
    "sheryl crow",
    "shut it down",
    "sicko mode",
    "sign of the times",
    "slow hands",
    "snake man pt. 1",
    "snake man pt. 2",
    "some things you don't forget",
    "somewhere on a beach",
    "spaghetti",
    "starboy",
    "still chose you",
    "sucker for pain",
    "talk about georgia",
    "tattoos and tequila",
    "the box",
    "there was this girl",
    "they don't know",
    "timmy turner",
    "too drunk to drive",
    "trauma",
    "trip",
    "truth is",
    "two ghosts",
    "unsteady",
    "what it feels like",
    "when to say when",
    "yellow flicker beat",
    "you could be that girl",
    "yummy",
]


# List sort function
#no_dupes = []
# [no_dupes.append(x) for x in pop_country_songs if x not in no_dupes]
# for song in no_dupes:
#    print('"' + song + '",')
