# These are US controlled songs that have previously appeared on the Hot 100
controlled_songs = [
    "ain't always the cowboy",
    "all around me",
    "all time low",
    "ballin'",
    "better days",
    "boo d up",
    "can't feel my face",
    "carolina",
    "championships",
    "cold water",
    "come around me",
    "dear today",
    "dedication",
    "despacito (remix) [feat. justin bieber]",
    "dinero",
    "dirt to dust",
    "earned it",
    "ever since new york",
    "everything i am",
    "flatliner",
    "from the dining table",
    "gettin' warmed up",
    "girl like me",
    "girl like you",
    "got what i got",
    "green light",
    "hell of a night",
    "higher",
    "i feel it coming",
    "i'll wait for you",
    "in a truck right now",
    "in my blood",
    "in my feelings",
    "intentions",
    "ispy",
    "jealous",
    "jesus is lord",
    "kiwi",
    "last time that i checc'd",
    "lean on",
    "let me love you",
    "liability",
    "little more (royalty)",
    "love you too late",
    "low life",
    "make me (cry)",
    "meet me in the hallway",
    "only angel",
    "panda",
    "party monster",
    "pray",
    "rearview town",
    "reason to drink",
    "renegades",
    "respect the game",
    "selah",
    "sicko mode",
    "sign of the times",
    "slow hands",
    "somewhere on a beach",
    "starboy",
    "sucker for pain",
    "the box",
    "there was this girl",
    "they don't know",
    "timmy turner",
    "trauma",
    "trip",
    "two ghosts",
    "unsteady",
    "what it feels like",
    "when to say when",
    "woman",
    "yellow flicker beat",
    "you could be that girl",
    "yummy",
]